export const TasksActionTypes = {
  ADD_TASK: 'ADD_TASK',
  MARK_TASK_FINISHED: 'MARK_TASK_FINISHED',
  UNMARK_TASK_FINISHED: 'UNMARK_TASK_FINISHED',
  DELETE_FINISHED_TASKS: 'DELETE_FINISHED_TASKS'
};
